AppBundle\Entity\Trash:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\TrashRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        file:
            targetEntity: File
            joinColumn:
                name: file_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
