version: '2'
services:
  web:
    build: docker/web
    working_dir: /var/project
    ports:
      - "3080:80"
    volumes:
      - ./home:/var/www
      - ./project:/var/project
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672
      - "15672:15672"