version: '2'
services:
  web:
    build: docker/web
    working_dir: /var/project
    ports:
      - "3080:80"
      - "2222:22"
    volumes:
      - ./home:/root
      - ./project:/var/project
    links:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:latest
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: homecloud
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672
      - "15672:15672"