# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  process_file_consumer:
    class: AppBundle\Consumer\ProcessFile
    arguments:
      - "@identity"

  file:
    class: AppBundle\Service\File
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@filesystem"
      - "%tmp_dir%"
      - "%storage_dir%"

  identity:
    class: AppBundle\Service\Identity
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@filesystem"
      - "%tmp_dir%"
      - "%storage_dir%"